###
POST http://localhost:3000/api/v1/employees/1
Content-Type: application/json
{
    "username": 1,
    "password": "123456",
    "phone": "123456",
    "fullName": "le dat",
    "age": 10,
    "avatar": "",
    "is_admin": false,
}